// Generated by CoffeeScript 1.6.2
var Char, String, Strings, h, mouseDown, mouseDrag, mouseMove, onFrame, onMouseDown, onMouseDrag, onMouseMove, onMouseUp, strings;

Path.prototype.setWidth = function(width) {
  this.segments[3].point.x = this.segments[0].point.x + width;
  return this.segments[2].point.x = this.segments[1].point.x + width;
};

Path.prototype.setHeight = function(height) {
  this.segments[1].point.y = this.segments[0].point.y + height;
  return this.segments[2].point.y = this.segments[3].point.y + height;
};

Path.prototype.reset = function() {
  this.setWidth(0);
  this.setHeight(0);
  return this.smooth();
};

h = {
  getRand: function(min, max) {
    return Math.floor((Math.random() * ((max + 1) - min)) + min);
  }
};

view.setViewSize($(window).outerWidth(), $(window).outerHeight());

mouseDown = null;

mouseMove = null;

mouseDrag = null;

String = (function() {
  function String(o) {
    var _base, _ref;

    this.o = o;
    this.touched = false;
    this.anima = false;
    this.colors = ["#69D2E7", "#A7DBD8", "#E0E4CC", "#F38630", "#FA6900", "#C02942", "#542437", "#53777A", "#ECD078", "#FE4365"];
    this.defaultColor = "#fff";
    this.makeAudio();
    this.makeBase();
    if ((_ref = (_base = this.o).stringsOffset) == null) {
      _base.stringsOffset = this.o.width * 15;
    }
  }

  String.prototype.makeAudio = function() {
    this.analyser = this.o.context.createAnalyser();
    this.audio = new Audio;
    this.audio.controls = true;
    this.audio.src = "sounds/" + this.o.guitar.sources[this.o.i % this.o.guitar.sources.length] + ".mp3";
    this.source = this.o.context.createMediaElementSource(this.audio);
    this.source.connect(this.analyser);
    return this.analyser.connect(this.o.context.destination);
  };

  String.prototype.makeBase = function() {
    this.base = new Path;
    this.xOffset = this.o.offset;
    this.base.add([this.o.offsetX_start, this.o.offsetY_start]);
    this.base.add([this.o.offsetX_end, this.o.offsetY_end]);
    this.startX = Math.min(this.o.offsetX_start, this.o.offsetX_end);
    this.startY = Math.min(this.o.offsetY_start, this.o.offsetY_end);
    this.endX = Math.max(this.o.offsetX_start, this.o.offsetX_end);
    this.endtY = Math.max(this.o.offsetY_start, this.o.offsetY_end);
    this.base.strokeColor = this.defaultColor;
    this.base.strokeWidth = this.o.width;
    return this.height = this.o.offsetY_end - this.o.offsetY_start;
  };

  String.prototype.change = function(e) {
    var point, _ref, _ref1, _ref2, _ref3;

    point = e.point;
    this.dir = null;
    if (e.delta.x > 0) {
      if (((e.point + e.delta).x >= this.startX) && (mouseDown.x < this.endX)) {
        if (((e.point + e.delta).y >= this.startY) && ((e.point + e.delta).y <= this.endtY)) {
          this.touched = true;
          if ((_ref = this.dir) == null) {
            this.dir = 'x';
          }
        }
      }
    }
    if (e.delta.x < 0) {
      if (((e.point - e.delta).x <= this.endX) && this.startX < mouseDown.x) {
        if (((e.point + e.delta).y > this.startY) && ((e.point + e.delta).y < this.endtY)) {
          this.touched = true;
          if ((_ref1 = this.dir) == null) {
            this.dir = 'x';
          }
        }
      }
    }
    if (e.delta.y < 0) {
      if (((e.point + e.delta).y <= this.endtY) && (this.startY < mouseDown.y)) {
        if (((e.point + e.delta).x > this.startX) && ((e.point + e.delta).x < this.endX)) {
          this.touched = true;
          if ((_ref2 = this.dir) == null) {
            this.dir = 'y';
          }
        }
      }
    }
    if (e.delta.y > 0) {
      if (((e.point + e.delta).y >= this.startY) && (this.o.offsetY_end > mouseDown.y)) {
        if (((e.point + e.delta).x > this.startX) && ((e.point + e.delta).x < this.endX)) {
          this.touched = true;
          if ((_ref3 = this.dir) == null) {
            this.dir = 'y';
          }
        }
      }
    }
    if (!this.touched) {
      return;
    }
    if (this.anima) {
      return;
    }
    this.base.segments[0].handleOut.y = point.y - this.startY;
    return this.base.segments[0].handleOut.x = point.x - this.startX;
  };

  String.prototype.animate = function() {
    this.touched = false;
    if (this.anima) {
      return;
    }
    this.anima = true;
    if (this.base.segments[0].handleOut.x === 0) {
      return;
    }
    this.soundX = parseInt(Math.abs(this.base.segments[0].handleOut.x));
    this.soundY = parseInt(Math.abs(this.base.segments[0].handleOut.y));
    this.soundY = this.soundY / (this.height + (2 * this.o.width));
    this.meter = Math.max(this.soundX, this.soundY);
    this.animateQuake();
    this.animateColor();
    return this.makeSound();
  };

  String.prototype.animateColor = function() {
    var from, it, to, _ref;

    if ((_ref = this.twColor) != null) {
      _ref.stop();
    }
    this.base.strokeColor = this.colors[this.index % this.colors.length];
    this.base.strokeColor.saturation = 1;
    from = {
      t: 0
    };
    to = {
      t: 1
    };
    this.twColor = new TWEEN.Tween(from).to(to, this.meter * 6);
    it = this;
    this.twColor.onUpdate(function() {
      it.base.strokeColor.brightness -= this.t / 8;
      if (it.base.strokeColor.brightness <= 0.1) {
        return it.base.strokeColor = it.defaultColor;
      }
    });
    return this.twColor.start();
  };

  String.prototype.animateQuake = function() {
    var from, it, to, _ref,
      _this = this;

    console.log;
    if ((_ref = this.tw) != null) {
      _ref.stop();
    }
    this.anima = true;
    from = {
      x: this.base.segments[0].handleOut.x,
      y: this.base.segments[0].handleOut.y,
      c: 1000 * this.index
    };
    to = {
      x: 0,
      y: 0,
      c: 0
    };
    this.tw = new TWEEN.Tween(from).to(to, 1000);
    this.tw.easing(function(t) {
      var b;

      b = Math.exp(-t * 10) * Math.cos(Math.PI * 2 * t * 10);
      if (t >= 1) {
        return 1;
      }
      return 1 - b;
    });
    it = this;
    this.tw.onUpdate(function() {
      it.base.segments[0].handleOut.x = this.x;
      return it.base.segments[0].handleOut.y = this.y;
    });
    this.tw.onComplete(function() {
      return _this.teardown();
    });
    return this.tw.start();
  };

  String.prototype.makeSound = function() {
    var from, it, to, _ref,
      _this = this;

    if ((_ref = this.twSound) != null) {
      _ref.stop();
    }
    from = {
      c: 2 * (this.index * 25) + this.soundX / 4,
      t: 1
    };
    to = {
      c: (this.index * 25) + this.soundX / 4,
      t: 0
    };
    this.twSound = new TWEEN.Tween(from).to(to, this.meter * 6);
    this.twSound.easing(function(t) {
      var b;

      b = Math.exp(-t * 10) * Math.cos(Math.PI * 2 * t * 10);
      if (t >= 1) {
        return 1;
      }
      return 1 - b;
    });
    it = this;
    this.twSound.onStart(function() {
      return _this.audio.play();
    });
    this.twSound.onComplete(function() {
      _this.stopAudio();
      return _this.teardown();
    });
    return this.twSound.start();
  };

  String.prototype.stopAudio = function() {
    this.audio.pause();
    return this.audio.currentTime = 0;
  };

  String.prototype.teardown = function() {
    this.stopAudio();
    this.base.segments[0].handleOut.x = 0;
    this.base.segments[0].handleOut.y = 0;
    this.anima = false;
    this.touched = false;
    return this.base.strokeColor = this.defaultColor;
  };

  return String;

})();

Char = (function() {
  function Char(o) {
    var i, item, string, _i, _len, _ref;

    this.o = o;
    this.width = this.o.width || 3;
    _ref = text[this.o.symbol];
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      item = _ref[i];
      string = new String({
        offsetX_start: item.offsetX_start,
        offsetX_end: item.offsetX_end,
        offsetY_start: item.offsetY_start,
        offsetY_end: item.offsetY_end,
        width: this.width,
        context: this.o.context,
        guitar: this.o.guitar,
        i: i
      });
      string.index = i;
      this.o.guitar.strings.push(string);
    }
  }

  return Char;

})();

Strings = (function() {
  function Strings(o) {
    this.initialOffset = 300;
    this.strings = [];
    this.stringWidth = 5;
    this.context = new webkitAudioContext();
    this.sources = ['a3', 'b2', 'd3', 'e2', 'g2', 'a2', 'c', 'd2', 'f', 'g1', 'a1', 'b1', 'd1', 'e1'];
    this.makeStrings();
    this.makebase();
    this.makeM();
  }

  Strings.prototype.makebase = function() {
    this.base = new Path.Circle([-100, -100], this.stringWidth * 2);
    this.base.fillColor = '#FFF';
    this.base.opacity = .25;
    this.guitar = new Raster('guitar');
    this.guitar.position.y += 450;
    return this.guitar.position.x += 450;
  };

  Strings.prototype.mouseMove = function(e) {
    return this.base.position = e.point;
  };

  Strings.prototype.makeStrings = function(cnt) {
    var i, o, offsetX, string, stringOffset, _i, _results;

    if (cnt == null) {
      cnt = 15;
    }
    _results = [];
    for (i = _i = 0; 0 <= cnt ? _i < cnt : _i > cnt; i = 0 <= cnt ? ++_i : --_i) {
      o = this.getOffset(i);
      stringOffset = this.stringWidth * 5;
      offsetX = this.initialOffset + (i * stringOffset);
      if (i === 13) {
        offsetX = this.initialOffset + (5 * stringOffset);
      }
      if (i === 14) {
        offsetX = this.initialOffset + (7 * stringOffset);
      }
      string = new String({
        offsetX_start: offsetX,
        offsetX_end: offsetX,
        offsetY_start: o.offsetY,
        offsetY_end: o.offsetY + o.length,
        width: this.stringWidth,
        context: this.context,
        guitar: this,
        i: i
      });
      string.index = i;
      _results.push(this.strings.push(string));
    }
    return _results;
  };

  Strings.prototype.makeM = function() {
    return new Char({
      context: this.context,
      guitar: this,
      symbol: 'M'
    });
  };

  Strings.prototype.getOffset = function(i) {
    var size;

    size = {};
    switch (i) {
      case 0:
        size.length = 130;
        size.offsetY = 705;
        break;
      case 1:
        size.length = 205;
        size.offsetY = 650;
        break;
      case 2:
        size.length = 375;
        size.offsetY = 490;
        break;
      case 3:
        size.length = 395;
        size.offsetY = 480;
        break;
      case 4:
        size.length = 405;
        size.offsetY = 475;
        break;
      case 5:
        size.length = 405;
        size.offsetY = 475;
        break;
      case 6:
        size.length = 860;
        size.offsetY = 20;
        break;
      case 7:
        size.length = 405;
        size.offsetY = 475;
        break;
      case 8:
        size.length = 405;
        size.offsetY = 475;
        break;
      case 9:
        size.length = 395;
        size.offsetY = 480;
        break;
      case 10:
        size.length = 375;
        size.offsetY = 490;
        break;
      case 11:
        size.length = 205;
        size.offsetY = 650;
        break;
      case 12:
        size.length = 130;
        size.offsetY = 705;
        break;
      case 13:
      case 14:
        size.length = 120;
        size.offsetY = 25;
    }
    return size;
  };

  Strings.prototype.makeQuake = function() {
    var i, string, _i, _len, _ref, _results;

    _ref = this.strings;
    _results = [];
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      string = _ref[i];
      _results.push(string.animate());
    }
    return _results;
  };

  Strings.prototype.changeStrings = function(point) {
    var i, string, _i, _len, _ref, _results;

    _ref = this.strings;
    _results = [];
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      string = _ref[i];
      _results.push(string.change(point));
    }
    return _results;
  };

  Strings.prototype.teardown = function() {
    var i, string, _i, _len, _ref, _results;

    TWEEN.removeAll();
    _ref = this.strings;
    _results = [];
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      string = _ref[i];
      _results.push(string.teardown());
    }
    return _results;
  };

  return Strings;

})();

strings = new Strings;

onFrame = function(e) {
  return TWEEN.update();
};

onMouseDrag = function(e) {
  strings.changeStrings(e);
  strings.mouseMove(e);
  return mouseDrag = e.point;
};

onMouseDown = function(e) {
  strings.teardown();
  return mouseDown = e.point;
};

onMouseUp = function(e) {
  return strings.makeQuake();
};

onMouseMove = function(e) {
  mouseMove = e.point;
  return strings.mouseMove(e);
};
